[2023-10-13 18:21:43,035] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:21:43,041] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:21:43,041] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:21:43,042] {taskinstance.py:1377} INFO - Starting attempt 2 of 7
[2023-10-13 18:21:43,042] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:21:43,052] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_redshift> on 2023-10-12 00:00:00+00:00
[2023-10-13 18:21:43,055] {standard_task_runner.py:52} INFO - Started process 206 to run task
[2023-10-13 18:21:43,057] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'load_data_redshift', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmpgckv6pp_', '--error-file', '/tmp/tmp27jbsvcl']
[2023-10-13 18:21:43,057] {standard_task_runner.py:80} INFO - Job 351: Subtask load_data_redshift
[2023-10-13 18:21:43,094] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [running]> on host 738c88afe20a
[2023-10-13 18:21:43,139] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=load_data_redshift
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-13 18:21:47,299] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials z9-20020aa785c9000000b006926e3dc2besm13887551pfn.108 - gsmtp')
[2023-10-13 18:21:47,299] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:21:57,026] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials z6-20020a17090abd8600b0027cbc50b826sm421669pjr.17 - gsmtp')
[2023-10-13 18:21:57,026] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:03,751] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b8-20020a637148000000b00589b7a9ef01sm3749244pgn.36 - gsmtp')
[2023-10-13 18:22:03,752] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:10,372] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials t123-20020a625f81000000b0068c10187dc3sm1912991pfb.168 - gsmtp')
[2023-10-13 18:22:10,372] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:16,775] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials y12-20020a170902ed4c00b001c60a548331sm4162834plb.304 - gsmtp')
[2023-10-13 18:22:16,775] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:24,218] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ja10-20020a170902efca00b001c62e3e1286sm4208172plb.166 - gsmtp')
[2023-10-13 18:22:24,218] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:31,649] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials f7-20020a17090274c700b001c61901ed2esm4172548plt.219 - gsmtp')
[2023-10-13 18:22:31,650] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:41,183] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials l4-20020a170902f68400b001c727d3ea6bsm4189142plg.74 - gsmtp')
[2023-10-13 18:22:41,183] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:49,718] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials x18-20020a17090300d200b001b8b2b95068sm4207461plc.204 - gsmtp')
[2023-10-13 18:22:49,718] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:58,742] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials p7-20020a170902e74700b001c74df14e72sm4181530plf.212 - gsmtp')
[2023-10-13 18:22:58,743] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:22:58,743] {python.py:173} INFO - Done. Returned value was: None
[2023-10-13 18:22:58,752] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=load_data_redshift, execution_date=20231012T000000, start_date=20231013T182143, end_date=20231013T182258
[2023-10-13 18:22:58,803] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-13 18:22:58,826] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
