[2023-10-13 18:54:08,621] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:54:08,627] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:54:08,627] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:54:08,628] {taskinstance.py:1377} INFO - Starting attempt 6 of 11
[2023-10-13 18:54:08,628] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:54:08,640] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_redshift> on 2023-10-12 00:00:00+00:00
[2023-10-13 18:54:08,643] {standard_task_runner.py:52} INFO - Started process 200 to run task
[2023-10-13 18:54:08,644] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'load_data_redshift', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '367', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmpr5cc1t70', '--error-file', '/tmp/tmpt7uyiclf']
[2023-10-13 18:54:08,645] {standard_task_runner.py:80} INFO - Job 367: Subtask load_data_redshift
[2023-10-13 18:54:08,682] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [running]> on host 738c88afe20a
[2023-10-13 18:54:08,728] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=load_data_redshift
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-13 18:55:05,021] {logging_mixin.py:115} INFO - type object 'datetime.datetime' has no attribute 'datetime'
[2023-10-13 18:55:05,021] {logging_mixin.py:115} INFO - Error al enviar el mail
[2023-10-13 18:55:05,022] {python.py:173} INFO - Done. Returned value was: None
[2023-10-13 18:55:05,031] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=load_data_redshift, execution_date=20231012T000000, start_date=20231013T185408, end_date=20231013T185505
[2023-10-13 18:55:05,077] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-13 18:55:05,096] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
